name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt
          python -m spacy download en_core_web_sm

      # Run tests
      - name: Run unit tests
        run: python -m unittest discover tests

      # Run linter (flake8)
      - name: Run flake8
        run: |
          pip install flake8
          flake8 src tests scripts --max-line-length=120 --ignore=E203,W503

      # Run type checking (mypy)
      - name: Run mypy
        run: |
          pip install mypy
          mypy src tests scripts --ignore-missing-imports --strict

      # Check code formatting (black)
      - name: Check code formatting with black
        run: |
          pip install black
          black --check src tests scripts --line-length=120
