# Configuration file for EWC-based Sentiment Analysis model

# Model parameters
model_name: "bert-base-uncased"
memory_size: 1000
learning_rate: 2e-5
batch_size: 16
max_length: 128
ewc_lambda: 0.4
epochs: 3
device: "auto"

# Dataset settings
domains:
  - movies
  - products

# Logging and saving
verbose: true
save_dir: "results/models/"
log_dir: "results/logs/"
results_dir: "results/plots/"