# Configuration file for GEM-based Named Entity Recognition model

# Model parameters
model_name: "bert-base-uncased"
memory_size: 1000
learning_rate: 2e-5
batch_size: 16
max_length: 512
epochs: 3
device: "auto"

# Dataset settings
domains:
  - news
  - medical
  - legal

# Logging and saving
verbose: true
save_dir: "results/models/"
log_dir: "results/logs/"
results_dir: "results/plots/"

# Additional GEM-specific parameters
margin: 0.5  # Margin for gradient projection in GEM