# Configuration file for Progressive Neural Network Language Modeling model

# Model parameters
model_name: "distilbert-base-uncased"
memory_size: 1000
learning_rate: 2e-5
batch_size: 16
max_length: 128
epochs: 3
device: "cuda"

# Dataset settings
domains:
  - general

# Logging and saving
verbose: true
save_dir: "results/models/"
log_dir: "results/logs/"
results_dir: "results/plots/"